export const MARKER_ACTION_CLIENT = Symbol('MARKER_ACTION_CLIENT');
export const MARKER_ACTION_EXECUTER = Symbol('MARKER_ACTION_EXECUTER');

export const MARKER_EVENT_CLIENT = Symbol('MARKER_EVENT_CLIENT');
export const MARKER_EVENT_EMITTER = Symbol('MARKER_EVENT_EMITTER');

export const MARKER_STATE_CLIENT = Symbol('MARKER_STATE_CLIENT');
export const MARKER_REACTIVE_STATE = Symbol('MARKER_REACTIVE_STATE');

export const MARKER_SERVICE_CLIENT = Symbol('MARKER_SERVICE_CLIENT');
export const MARKER_SERVICE = Symbol('MARKER_SERVICE');

export const MARKER_MODULE_CLIENT = Symbol('MARKER_MODULE_CLIENT');
export const MARKER_MODULE = Symbol('MARKER_MODULE');
